#!/usr/bin/env python3
"""
Canonical production deploy — git is the single source of truth.

  1. Build dashboard locally
  2. Write production.manifest.json (commit + bundle hashes)
  3. Commit & push to GitHub
  4. VPS: git pull origin/main (run setup_vps_git.py first if needed)
  5. Upload static/ (pre-built bundle — do not rely on VPS npm build)
  6. Restart PM2 + verify live site matches git

Usage (PowerShell):
  $env:VPS_PASSWORD = '...'
  python scripts/deploy_prod.py

Never use scripts/_vps_deploy_*.py for routine updates — they bypass git and cause drift.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from scripts.prod_sync_common import (  # noqa: E402
    REMOTE,
    bump_build_stamp,
    ssh_connect,
    ssh_run,
    upload_tracked_tree,
    write_manifest,
    write_vps_deploy_marker,
)

STATIC_DIR = REPO / "static"


def run(cmd: list[str], *, cwd: Path | None = None, timeout: int = 600) -> None:
    print(f">>> {' '.join(cmd)}")
    subprocess.run(cmd, cwd=cwd or REPO, check=True, timeout=timeout)


def git(*args: str) -> str:
    out = subprocess.check_output(["git", *args], cwd=REPO, text=True)
    return out.strip()


def upload_static(sftp) -> int:
    count = 0
    for dirpath, _dirnames, filenames in os.walk(STATIC_DIR):
        for name in filenames:
            local = Path(dirpath) / name
            rel = local.relative_to(STATIC_DIR).as_posix()
            remote = f"{REMOTE}/static/{rel}"
            remote_dir = os.path.dirname(remote).replace("\\", "/")
            parts = remote_dir.split("/")
            path = ""
            for p in parts:
                if not p:
                    continue
                path += f"/{p}"
                try:
                    sftp.stat(path)
                except OSError:
                    try:
                        sftp.mkdir(path)
                    except OSError:
                        pass
            sftp.put(str(local), remote)
            count += 1
    return count


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    ap = argparse.ArgumentParser(description="Deploy to production via git")
    ap.add_argument("--skip-build", action="store_true", help="Use existing static/ build")
    ap.add_argument("--skip-push", action="store_true", help="Deploy current HEAD without pushing")
    ap.add_argument("--no-commit", action="store_true", help="Do not auto-commit manifest/static")
    args = ap.parse_args()

    password = os.environ.get("VPS_PASSWORD", "")
    if not password:
        print("Set VPS_PASSWORD", file=sys.stderr)
        return 1

    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    if branch != "main":
        print(f"WARNING: not on main (on {branch})", file=sys.stderr)

    dirty_before = git("status", "--porcelain")
    if dirty_before and not args.no_commit:
        print("Note: uncommitted changes will be included in deploy commit.")

    # ── Build ──────────────────────────────────────────────────────────
    if not args.skip_build:
        bump_build_stamp()
        run(["npm", "run", "build"], cwd=REPO / "dashboard", timeout=300)

    if not (STATIC_DIR / "index.html").is_file():
        print("static/index.html missing — build failed?", file=sys.stderr)
        return 1

    manifest = write_manifest()
    print(f"Manifest: {manifest.get('js')} @ {manifest.get('git_commit_short')}")

    # ── Commit & push ────────────────────────────────────────────────────
    if not args.no_commit:
        paths = [
            "static/index.html",
            "static/production.manifest.json",
            "static/assets",
            "dashboard/src/config.js",
        ]
        subprocess.run(["git", "add", *paths], cwd=REPO, check=False)
        # Also add any new hashed bundle files
        js_rel = manifest.get("js", "").replace("assets/", "static/assets/")
        css_rel = manifest.get("css", "").replace("assets/", "static/assets/")
        for rel in (js_rel, css_rel):
            if rel and (REPO / rel).is_file():
                subprocess.run(["git", "add", rel], cwd=REPO, check=False)

        status = git("status", "--porcelain")
        if status:
            short = git("rev-parse", "--short", "HEAD")
            msg = f"chore(deploy): production build {short}\n\nAuto-generated by scripts/deploy_prod.py"
            run([
                "git", "-c", "user.name=codetrust2025-spec",
                "-c", "user.email=codetrust2025@gmail.com",
                "commit", "-m", msg,
            ])
        else:
            print("No git changes to commit (manifest/static unchanged)")

    if not args.skip_push:
        run(["git", "push", "origin", "main"], timeout=120)

    head = git("rev-parse", "HEAD")
    print(f"Deploying commit {head[:7]}...")

    # ── VPS: upload git-tracked tree (private repo — no git pull on VPS) ─
    client = ssh_connect(password)
    try:
        sftp = client.open_sftp()
        n_code = upload_tracked_tree(sftp, client)
        n_static = upload_static(sftp)
        sftp.close()
        print(f"Uploaded {n_code} tracked files + {n_static} static files")
        write_vps_deploy_marker(client, head)

        code, out, err = ssh_run(
            client,
            f"cd {REMOTE} && pm2 restart telegram-backend --update-env && sleep 2 && "
            f"curl -sf -m 5 http://127.0.0.1:8000/health && echo HEALTH_OK",
            timeout=60,
        )
        print(out)
        if "HEALTH_OK" not in out:
            print("WARN: health check unclear — check pm2 logs", file=sys.stderr)
    finally:
        client.close()

    # ── Verify ───────────────────────────────────────────────────────────
    print("\n--- Post-deploy verification ---")
    verify = subprocess.run(
        [sys.executable, str(REPO / "scripts" / "verify_git_prod_sync.py")],
        cwd=REPO,
        env={**os.environ, "VPS_PASSWORD": password},
    )
    return verify.returncode


if __name__ == "__main__":
    raise SystemExit(main())
